### ISSUE TITLE
in MACOS, MINIKUBE + DOCKER driver , the admin-service startup ERROR

### ISSUE THREAD

**Issue by PeterDev1024** [piomin/sample-spring-microservices-kubernetes#35]
the error log below:

Couldn't retrieve status for Instance(id=6858a2bf2471, version=0, registration=Registration(name=department, managementUrl=http://10.244.0.58:8080/actuator, healthUrl=http://10.244.0.58:8080/actuator/health, serviceUrl=http://10.244.0.58:8080/, source=discovery), registered=true, statusInfo=StatusInfo(status=UNKNOWN, details={}), statusTimestamp=2023-08-13T07:42:52.639162335Z, info=Info(values={}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=[http://10.244.0.58:8080/actuator/health)}](http://10.244.0.58:8080/actuator/health)%7D)), buildVersion=null, tags=Tags(values={}))

**Comment by piomin** [comment]
How did you run it?
