### ISSUE TITLE
Incorrect dependency on admin-service

### ISSUE THREAD

**Issue by ThiagoBfim** [piomin/sample-spring-microservices-kubernetes#4]
https://github.com/piomin/sample-spring-microservices-kubernetes/blob/83172de89abbead8fe9b523eb286a1d799ed09af/admin-service/pom.xml#L38

It seems incorrect, it should use		`<artifactId>spring-cloud-starter-kubernetes</artifactId>`

https://github.com/codecentric/spring-boot-admin/issues/1582

**Comment by piomin** [comment]
Hi, it works fine in the latest
