### ISSUE TITLE
skaffold dev always exit

### ISSUE THREAD

**Issue by yuxh** [piomin/sample-spring-microservices-kubernetes#44]
I run command from main branch :
```
❯ skaffold dev    
Generating tags...
 - piomin/admin -> piomin/admin:2cd5a58-dirty
Checking cache...
 - piomin/admin: Found Locally
Cleaning up...
 - No resources found
missing Resource metadata
```
any idea how to fix this? windows+ docker desktop 4.22 (docker engine24.0.5, k8s 1.27.2)+ skaffold 2.7.1

**Comment by piomin** [comment]
Strange. I'm not very sure why it happens. Did you try with another app in the repo?
